# Generated by Django 5.2 on 2025-05-20 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_mymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(default=datetime.date(2025, 5, 20)),
        ),
    ]
