# Generated by Django 5.2 on 2025-05-21 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_email_student_enrollment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(
                default=datetime.date(2025, 5, 21), verbose_name="Дата регистрации"
            ),
        ),
    ]
