# Generated by Django 5.2 on 2025-05-23 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_enrollment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(
                default=datetime.date(2025, 5, 23), verbose_name="Дата регистрации"
            ),
        ),
    ]
