# Generated by Django 5.2 on 2025-06-02 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_student_enrollment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата регистрации"
            ),
        ),
    ]
