# Generated by Django 5.2 on 2025-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Всего просмотров"
            ),
        ),
    ]
