# Generated by Django 5.2 on 2025-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0004_dog_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dog",
            options={
                "ordering": ["breed", "name"],
                "permissions": [
                    ("can_edit_breed", "Can edit breed"),
                    ("can_edit_description", "Can edit description"),
                ],
                "verbose_name": "Собака",
                "verbose_name_plural": "Собаки",
            },
        ),
        migrations.AddField(
            model_name="dog",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Укажите описание собаки",
                null=True,
                verbose_name="Описание собаки",
            ),
        ),
    ]
